### ISSUE TITLE
The combination of listenXHR()/getXHR(...) doesn't work after the browser page self refreshes.

### ISSUE THREAD

**Issue by simeonmalchev** [cortexmg/nightwatch-xhr#27]
Hi there,

First to say thank you for releasing nightwatch-xhr, it's a very useful library.

I got one problem which I'm not sure how to workaround, I'm using the following structure:

`      browser
          .url(some_url)
          .waitForElementVisible(someLink, 7000)
          .click(someLink)
          .listenXHR()
          .doStuff()
          .getXHR("some_starting_path", 15000, xhrs => do_something())
`

This works fine and I receive in the xhrs array all interactions as expected, however, if the monitored page does an automatic refresh, imagine the page executes 'location.reload()' on the 7th second, then the xhrs array doesn't contain any data, i.e., it is empty. 

Is there any way I can solve/workaround this problem so that I receive in the callback all xhrs interaction that have happened before and after the page refreshes?  Or maybe any fix that can be released for this? Just to make this clear, there are xhr interaction executed from the page in question before and after the page refreshes.

Cheers,
Simeon

**Comment by simeonmalchev** [comment]
Btw, I found myself a workaround for this problem, instead of waiting for the monitored page to self refresh, I can myself navigate twice to the page via clicks and I can this way intercept all the xhr interactions that I need. I'll still leave this issue open for a few more days in case you have an update or suggestions on it, and I'll close it after that.

**Comment by JalilArfaoui** [comment]
Hello @simeonmalchev 

Unfortunately, this is the expected behavior and I can't think of any solution to this. 

The thing is that we make this module work by modifying the **current** XmlHttpRequest of the page, in order to listen to what it does (that's what `listenXHR` does). But when the page gets completely reloaded, the `window` gets re-recreated and the effect of `listenXHR` is gone, so we're not "listening" anymore. 

The only way would be to call `listenXHR` right after the reload if you can detect it, but it's pretty hacky because: 
 - All listened requests before the refresh will be gone (if not retreived with `getXHR`)
 - Any request triggered before `listenXHR` is setup will not be catched

**Comment by simeonmalchev** [comment]
No worries, thank for explaining, I'll close the issue.

**Comment by kretschmannj** [comment]
@JalilArfaoui I'm also having the issue where the page is being reloaded and I'm losing the captured XHRs from the initial page load.  The page load happens so quickly that I'm unable to use getXHR to capture the XHRs before the page is reloaded.  Using devtools I can see that there are two XHR requests that are happening after the initial page load but I'm unable to capture them before the page is reloaded.  Is there a workaround or potential fix that would keep ALL of the captured XHRs and not dispose of them when the page is reloaded?
